Repository wildcodeschool-2025-03/toulouse-wcs-gaming, pull requests merged in 2025-04, with the labels that each got.

#3 feat(App.tsx): change the h1 content
  client/src/App.tsx
Labels: REVIEWED, CORRECTED

#4 feat: modify h2
  client/src/App.tsx
Labels: REVIEWED, CORRECTED

#5 feat: create navbar
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/favicon.svg
  client/src/assets/images/loupe_search.svg
  client/src/components/Navbar.tsx
Labels: CHANGES REQUESTED, REVIEWED, CORRECTED

#8 S1 us02/feature searchbar
  client/src/App.css
  client/src/components/Navbar.tsx
  client/src/components/SearchBar.tsx
Labels: REVIEWED, CONFLICTS RESOLVED

#7 S1 us05/feature footer component
  .git-hooks/commit-msg
  .git-hooks/pre-commit
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/LOGO-NOIR.svg
  client/src/assets/images/assasin.png
  client/src/assets/images/recon-recon.png
  client/src/components/Footer.tsx
  client/src/components/Page404.tsx
  client/src/main.tsx
Labels: REVIEWED, CONFLICTS RESOLVED

#9 feat: improve game card
  client/index.html
  client/src/App.css
  client/src/assets/images/platforms/NintendoIcon.svg
  client/src/assets/images/platforms/PcIcon.svg
  client/src/assets/images/platforms/PsIcon.svg
  client/src/assets/images/platforms/XboxIcon.svg
  client/src/components/GameCard.tsx
Labels: REVIEWED

#10 S1 us17/feature header
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/image-header-v2.png
  client/src/assets/images/image-header.jpg
  client/src/components/Header.tsx
Labels: REVIEWED, CONFLICTS RESOLVED

#11 S1 us03/feature top rated games
  client/src/App.css
  client/src/App.tsx
  client/src/components/GameCard.tsx
  client/src/components/GameCardsArea.tsx
  client/src/components/TopGames.tsx
Labels: REVIEWED, CONFLICTS RESOLVED

#12 fix: merge dev and cards
  client/src/components/GameCard.tsx
Labels: REVIEWED

#15 S2 us03/feature detail page
  client/src/App.css
  client/src/App.tsx
  client/src/components/GameCard.tsx
  client/src/components/GameDetail.tsx
  client/src/main.tsx
  client/src/services/Reset.css
  client/src/services/UseFetchGames.tsx
  client/src/types/types.tsx
Labels: REVIEWED

#13 feat: @media screen
  client/src/App.css
  client/src/components/SearchBar.tsx
Labels: CORRECTED, CONFLICTS RESOLVED
