Repository wildcodeschool-2025-03/toulouse-wcs-gaming, pull requests merged in 2025-05, with the labels that each got.

#14 S1 us09/feature mention
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/assassin.png
  client/src/assets/images/recon-recon.png
  client/src/components/Category.tsx
  client/src/components/Footer.tsx
  client/src/components/MentionLegal.tsx
  client/src/components/Page404.tsx
  client/src/main.tsx
  client/src/services/UseFetchGames.tsx
Labels: REVIEWED, CORRECTED

#16 feat: add suggestion in game detail page
  client/src/App.css
  client/src/App.tsx
  client/src/components/GameDetail.tsx
  client/src/components/Suggestion.tsx
  client/src/components/TopGames.tsx
Labels: REVIEWED

#18 S2 us10/feature news
  client/src/App.css
  client/src/App.tsx
  client/src/components/NewSection.tsx
Labels: REVIEWED, CONFLICTS RESOLVED

#21 S0 us0/style
  client/src/App.css
  client/src/App.tsx
  client/src/components/Category.tsx
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/MentionLegal.tsx
  client/src/components/SearchBar.tsx
  client/src/components/TopGames.tsx
Labels: REVIEWED

#23 S2 us10/feature news
  client/src/App.css
  client/src/components/Navbar.tsx
  client/src/components/NewSection.tsx
  client/src/components/SearchBar.tsx
  client/src/components/SearchResults.tsx
  client/src/components/TopGames.tsx
Labels: REVIEWED

#24 feat: add most popular
  client/src/App.tsx
  client/src/components/MostPopular.tsx
Labels: REVIEWED

#20 S1 us11/feature button platform
  client/src/App.css
  client/src/App.tsx
  client/src/components/ButtonsPlatform.tsx
  client/src/components/CategoryButtons.tsx
  client/src/main.tsx
  package-lock.json
Labels: REVIEWED, CORRECTED, CONFLICTS RESOLVED

#29 S3 us12/feature category v2
  client/src/App.css
  client/src/components/GenreDetails.tsx
  client/src/services/UseFetchGames.tsx
Labels: REVIEWED, CONFLICTS RESOLVED

#30 S1 us11/feature button platform
  client/src/App.css
  client/src/components/ButtonsPlatform.tsx
Labels: REVIEWED

#31 fix: fix search bar range
  client/src/components/Navbar.tsx
Labels: REVIEWED

#32 S0 us0/fix searchbar
  client/src/components/CategoryButtons.tsx
  client/src/services/UseFetchGames.tsx
Labels: REVIEWED

#34 S0 us0/finalise style
  client/src/App.css
  client/src/App.tsx
  client/src/components/ButtonsPlatform.tsx
  client/src/components/CategoryButtons.tsx
  client/src/components/GenreDetails.tsx
  client/src/components/HorrorSection.tsx
  client/src/components/Pub.tsx
  client/src/components/Suggestion.tsx
  client/src/services/UseFetchGames.tsx
  package-lock.json
Labels: REVIEWED

#35 S1 us11/feature button platform
  client/src/App.css
  client/src/components/Category.tsx
Labels: REVIEWED
